### PR TITLE
Support py2 and py3

### PR DESCRIPTION
**Pull request by laserson**
`setup.py` will now install the py2 or py3 compatible version depending on which version of python is being run.

Main changes: `PyInt` and `PyString` are gone.

### CODE REVIEW

**Comment by laserson** [comment]
Merge the two `*.i` files by using `%#ifdef` directives, per @toddlipcon's request.

**Comment by toddlipcon** [comment]
hrm, the new patch doesn't seem to be different... maybe I'm looking at the wrong thing, but I still see two separate .i files.

**Comment by laserson** [comment]
Oh yeah, this PR is the original version I sent you, but it's broken by errors that looks like:

```
self = <sasl.saslwrapper.Client; proxy of <Swig Object of type 'saslwrapper::Client *' at 0x7fb8dcdc2780> >
challenge = b'`\x81\x9e\x06\t*\x86H\x86\xf7\x12\x01\x02\x02\x02\x00o\x81\x8e0\x81\x8b\xa0\x03\x02\x01\x05\xa1\x03\x02\x01\x0f\xa2\...8\xa3U\x8f:e3gox:\xee\x9f\nS\x12\xe9\xcd\x01\xe9\xf8\xbe:9I\xbb}\xed\xcd\nq\x94\x02\x8e8>\xb7O\xbc"q-\xcd2g\xc6h2\xdbk'

    def step(self, challenge: 'std::string const &') -> "bool":
>       return _saslwrapper.Client_step(self, challenge)
E       TypeError: in method 'Client_step', argument 2 of type 'std::string const &'

../../sasl/saslwrapper.py:183: TypeError
```

**Comment by laserson** [comment]
I've abandoned this line of inquiry.  I will soon submit a PR that switches to using Cython.

**Pull request closed without merging**
